name: Cloud Build

on:
  workflow_dispatch: # Allows manual or programmatic triggering

jobs:
  build:
    runs-on: ubuntu-latest # Use GitHub-hosted runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Fetches repository code

      - name: Execute CI Pipeline Logic
        run: dotnet run --project ./ci-program/CIProgram.csproj
